export const IMAGES_URL = {
    BACKGROUND: "../public/images/backpicture.png",
    ARENA_LOGO: "../public/images/Arena_Verlag_Logo.png",
    RARAMOUNT_LOGO: "../public/images/Paramount_Network.png",
    REDE_LOGO: "../public/images/Rede_Telecine_vertical_logo.png",
    RTS1_LOGO: "../public/images/RTS_1_logo_2019.png",
    SONY_LOGO: "../public/images/Sony_Movies_Logo.png",
    BACK_ICON: "../public/images/back_icon.png",
    PLAY: "../public/images/play.png",
    LOGO: "../public/images/logo.png",
    IMAGE_NOT_FOUND: "../public/images/no_poster.png",
    SHINDIRI: "../public/images/shindiri.png",
    BACKGROUND_SHINDIRI: "../public/images/backpicture.jpg",
    LOADER: "../public/images/spinner.svg",
}

export const API_URLS = {
    CREDITS: "/credits",
    MOVIE_DETAIL: `/movie`,
    SERIES_DETAIL: "/tv",
    GET_MOVIES: `/movie/popular`,
    GET_SERIES: `/tv/popular`,
    GET_MOVIE_GENRES_LIST: `/genre/movie/list`,
    GET_MOVIES_BY_GENRES: `/discover/movie`,
    GET_SERIES_GENRES_LIST: `/genre/tv/list`,
    GET_SERIES_BY_GENRES: `discover/tv`,
    IMAGES: `/images`,
    NOW_PLAYING_MOVIES: `/movie/now_playing`,
    ON_THE_AIR_SERIES: `/tv/on_the_air`,
} 